/**
 * Reverse Execution Engine
 * 
 * Analyzes target output and generates execution plans by working backwards
 * from the desired result to the required code and module invocations.
 */

import type { LegionModule, ExecutionPlan, ExecutionStep, IOOperation } from '../types';
import type { IOTracker } from './io';

/**
 * Pattern matchers for common output patterns
 */
const OUTPUT_PATTERNS: Array<{
  pattern: RegExp;
  name: string;
  generate: (match: RegExpMatchArray) => string;
}> = [
  {
    pattern: /print\s*\(\s*["'](.+?)["']\s*\)/,
    name: 'python-print',
    generate: (match) => `# Generated by Legion Kernel
# Pattern: Python print statement
# Target: print("${match[1]}")

print("${match[1]}")
`
  },
  {
    pattern: /console\.log\s*\(\s*["'](.+?)["']\s*\)/,
    name: 'js-console',
    generate: (match) => `// Generated by Legion Kernel
// Pattern: JavaScript console.log
// Target: console.log("${match[1]}")

console.log("${match[1]}");
`
  },
  {
    pattern: /echo\s+["']?(.+?)["']?/,
    name: 'shell-echo',
    generate: (match) => `# Generated by Legion Kernel
# Pattern: Shell echo
# Target: echo ${match[1]}

echo "${match[1]}"
`
  },
  {
    pattern: /成功 | success|success/i,
    name: 'success-message',
    generate: () => `# Generated by Legion Kernel
# Pattern: Success message

print("成功")
`
  }
];

/**
 * Reverse execute from a target output string
 */
export async function reverseExecute(
  targetOutput: string,
  modules: Map<string, LegionModule>,
  io: IOTracker
): Promise<ExecutionPlan> {
  const steps: ExecutionStep[] = [];
  const requiredModules: string[] = [];
  const ioOperations: IOOperation[] = [];

  // Step 1: Analyze the target output
  const analysis = analyzeOutput(targetOutput);
  steps.push({
    order: 1,
    action: 'analyze',
    description: `Analyzed output: detected ${analysis.patterns.length} pattern(s)`,
    code: `// Detected patterns: ${analysis.patterns.map(p => p.name).join(', ')}`
  });

  // Step 2: Find matching modules
  for (const [id, mod] of modules) {
    if (mod.trigger && targetOutput.includes(mod.trigger)) {
      requiredModules.push(id);
      steps.push({
        order: steps.length + 1,
        action: 'invoke',
        module: id,
        description: `Invoke module: ${mod.name}`,
        code: `await kernel.modules.get('${id}').handler(ctx)`
      });
    }
  }

  // Step 3: Generate code based on patterns
  const generatedCode = generateCodeForOutput(targetOutput, analysis);
  steps.push({
    order: steps.length + 1,
    action: 'generate',
    description: `Generated ${generatedCode.split('\n').length} lines of code`,
    code: generatedCode
  });

  // Step 4: Create execution recommendations
  const recommendations = generateRecommendations(analysis, requiredModules);
  steps.push({
    order: steps.length + 1,
    action: 'recommend',
    description: `Generated ${recommendations.length} recommendation(s)`,
    code: recommendations.join('\n')
  });

  // Step 5: Log the reverse execution
  const logEntry = {
    type: 'reverse_execution',
    target: targetOutput,
    patterns: analysis.patterns.map(p => p.name),
    modules: requiredModules,
    timestamp: Date.now()
  };
  
  const logPath = `reverse/${Date.now()}.json`;
  await io.write(logPath, JSON.stringify(logEntry, null, 2));
  ioOperations.push({
    type: 'write',
    path: logPath,
    content: JSON.stringify(logEntry, null, 2),
    timestamp: Date.now()
  });

  return {
    targetOutput,
    steps,
    requiredModules,
    ioOperations,
    analysis,
    generatedCode
  };
}

/**
 * Analyze output string for known patterns
 */
function analyzeOutput(output: string): {
  patterns: Array<{ name: string; match: RegExpMatchArray }>;
  complexity: 'simple' | 'moderate' | 'complex';
  estimatedLines: number;
} {
  const patterns: Array<{ name: string; match: RegExpMatchArray }> = [];
  
  for (const pattern of OUTPUT_PATTERNS) {
    const match = output.match(pattern.pattern);
    if (match) {
      patterns.push({ name: pattern.name, match });
    }
  }

  // Estimate complexity
  let complexity: 'simple' | 'moderate' | 'complex' = 'simple';
  if (output.includes('\n') || output.length > 100) {
    complexity = 'moderate';
  }
  if (output.includes('{') || output.includes('function') || output.includes('class')) {
    complexity = 'complex';
  }

  // Estimate lines
  const estimatedLines = output.split('\n').length;

  return { patterns, complexity, estimatedLines };
}

/**
 * Generate code for the target output
 */
function generateCodeForOutput(
  targetOutput: string,
  analysis: ReturnType<typeof analyzeOutput>
): string {
  if (analysis.patterns.length === 0) {
    // No known patterns - generate generic template
    return `# Generated by Legion Kernel
# Target output: ${escapeCode(targetOutput)}
# No matching patterns found - manual implementation required

# TODO: Implement logic to produce:
# ${targetOutput.split('\n').map(l => '# ' + l).join('\n')}
`;
  }

  // Use the first matching pattern to generate code
  const pattern = OUTPUT_PATTERNS.find(p => p.name === analysis.patterns[0].name);
  if (pattern) {
    return pattern.generate(analysis.patterns[0].match);
  }

  // Fallback
  return `# Generated by Legion Kernel
# Target: ${escapeCode(targetOutput)}
print("成功")
`;
}

/**
 * Generate recommendations based on analysis
 */
function generateRecommendations(
  analysis: ReturnType<typeof analyzeOutput>,
  modules: string[]
): string[] {
  const recommendations: string[] = [];

  if (analysis.patterns.length === 0) {
    recommendations.push('Consider creating a custom module for this output pattern');
  }

  if (modules.length === 0) {
    recommendations.push('No modules matched - consider registering a module with appropriate trigger');
  }

  if (analysis.complexity === 'complex') {
    recommendations.push('Complex output detected - consider breaking into smaller modules');
  }

  recommendations.push(`Estimated implementation: ${analysis.estimatedLines} line(s)`);

  return recommendations;
}

/**
 * Escape special characters for code comments
 */
function escapeCode(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/\t/g, '\\t');
}

export default reverseExecute;
